### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by pedmindset** [jacksleight/statamic-miniset#1]
How do you actually use this add-on... Finding it difficult to figure it out completely

**Comment by jacksleight** [comment]
Within the blueprint or fieldset editor create a new "Miniset" or "Miniset Classes" field, and then within that field's configuration you can add all your option fields under the "Fields" section. That will then appear as a compact set of fields within the edit form.

Hope that helps. Let me know if you're having trouble with anything in particular.

**Comment by jacksleight** [comment]
Going to close this, shout if you need any further help.
