### ISSUE TITLE
Width options ignored in deeply nested replicator sets

### ISSUE THREAD

**Issue by pdipatrizio** [jacksleight/statamic-miniset#3]
I added a miniset field in a replicator set and configured the fields' widths to 50% but it was ignored and they were displayed at 100% width.

The replicator hierarchy is:
Section > Cards > Card > **Image** (Options miniset field is here)

Out of curiosity, I tested the miniset field 1 level higher (on the **Card** set) and the configured widths worked. So, it seems to only be an issue after the 3rd level of nesting.

As I'm finishing typing this, I'm wondering if this is a Statamic "issue" due to Statamic itself ignoring width configurations past 3 levels of nesting? Even if that's the case, is this something you could override for miniset fields? (since miniset fields are so much more compact, custom widths can still have relevance in deeply nested sets).

![Screen Shot 2023-04-14 at 10 59 53 AM](https://user-images.githubusercontent.com/19377737/232082558-c0f89d29-b715-4d34-996b-168fba76459a.png)

**Comment by jacksleight** [comment]
Hey. Yep this is Statamic, it applies the widths differently depending on the container size. It is something I can override, there's actually already one override that stops 25% fields going to 100%, but currently what I can do is limited by the container widths that Statamic checks for. And at some point you would still want 50% fields to go full width.

I'll take a look at what's currently possible. In v4 I think this is switching to container queries, so it should be much easier to override with custom container widths.

**Comment by jacksleight** [comment]
In the current version (that works with Statamic 3.4) I'm not really able to override this.

But in the next version (that works with 4.0) there will be improved width breakpoints for 1/2 and 1/3 wide fields.

![Screenshot 2023-04-18 at 14 47 49](https://user-images.githubusercontent.com/126740/232797670-e46b9d67-53e7-46de-bda0-f485dfe0c4ea.png)

**Comment by jacksleight** [comment]
This now works better in 1.0.0 (https://github.com/jacksleight/statamic-miniset/releases/tag/1.0.0)
